kind: Service
apiVersion: v1
metadata:
  name: python-service
spec:
  type: LoadBalancer
  ports:
    - port: 8443
  selector:
    app: python
---
apiVersion: v1
kind: Pod
metadata:
  name: static-python-web
  labels:
    app: python
spec:
  containers:
    - name: web
      image: google/python-hello
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    app: nodejs
---
apiVersion: v1
kind: Pod
metadata:
  name: static-node-web
  labels:
    app: nodejs
spec:
  containers:
    - name: web
      image: heroku/nodejs-hello-world
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: apache-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: apache
---
apiVersion: v1
kind: Pod
metadata:
  name: static-apache-web
  labels:
    app: apache
spec:
  containers:
    - name: web
      image: tomcat
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
