kind: Service
apiVersion: v1
metadata:
  name: python-service
spec:
  selector:
    app: python
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: static-python-web
  labels:
    app: python
spec:
  containers:
    - name: web
      image: google/python-hello
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: static-node-web
  labels:
    app: nodejs
spec:
  containers:
    - name: web
      image: heroku/nodejs-hello-world
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: apache-service
spec:
  selector:
    app: apache
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: static-apache-web
  labels:
    app: apache
spec:
  containers:
    - name: web
      image: tomcat
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
